---

- name: download swarm jar v{{ swarm_version }}
  get_url: url={{ swarm_topurl }}/{{ swarm_version }}/swarm-client-{{ swarm_version }}-jar-with-dependencies.jar
           dest={{ swarm_jar }} mode=0444
           owner=root group=root

- name: Systemd unit
  template: src=etc/systemd/system/swarm.service.j2
            dest=/etc/systemd/system/swarm.service
            mode=0444 owner=root group=root
  notify: 
    - reload systemd
    - bounce swarm

- name: start swarm
  service: name=swarm state=started enabled=yes
