- hosts: masters
  sudo: yes
  vars:
    jenkins_home: /var/lib/jenkins
# https://wiki.jenkins-ci.org/display/JENKINS/Jenkins+CLI wrapper script
    jenkins_cli_command: /usr/local/bin/jenkins-cli
  roles:
    - jenkins/account
    - repos/jenkins
# this role sets a 'java8_home' var
    - java/eight
# basic master using the specifed JVM.
    - { role: jenkins/master, java_home: "{{ java8_home }}" }

- hosts: slaves
  sudo: yes
  vars:
    jenkins_home: /var/jenkins-slave
  roles:
    - java/eight
    - jenkins/account
