- hosts: masters
  sudo: yes
  vars:
    jenkins_user: jenkins
    jenkins_home: /var/lib/jenkins
  roles:
    - java/eight
    - jenkins/account
    - repos/jenkins

- hosts: slaves
  sudo: yes
  vars:
    jenkins_user: jenkins
    jenkins_home: /var/jenkins-slave
  roles:
    - java/eight
    - jenkins/account
