- hosts: masters
  sudo: yes
  vars:
    jenkins_user: jenkins
    jenkins_home: /var/lib/jenkins
    jenkins_http_port: 8080
    jenkins_ajp_port: -1
  roles:
    - jenkins/account
    - repos/jenkins
# this role sets a 'java8_home' var
    - java/eight
    - { role: jenkins/master, java_home: "{{ java8_home }}" }

- hosts: slaves
  sudo: yes
  vars:
    jenkins_user: jenkins
    jenkins_home: /var/jenkins-slave
  roles:
    - java/eight
    - jenkins/account
