---

#NB: if you want a specific release
# (preferably LTS), set it on an inventory
# (see vagrant/hosts)

jenkins_rpm: jenkins

# override this in once you have a good JVM;
# /usr may vary depending on 'alternatives' system
java_home: /usr
